---
- name: Ensure that the Apache web server is not installed in order to avoid conflicts with Nginx
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ apache_packages_to_remove }}"

- name: Install Nginx
  apt:
    name: nginx

- name: Update Nginx configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Nginx

- name: Set up Nginx vhost directories
  file:
    path: /etc/nginx/{{ item }}
    state: directory
  with_items:
    - sites-available
    - sites-enabled
